# Offline-only, byte-verified nlohmann_json 3.11.3. No FetchContent fallback.
set(_qingying_json_root "${CMAKE_CURRENT_LIST_DIR}/../vendor/nlohmann_json")
foreach(_qingying_json_file IN ITEMS include/nlohmann/json.hpp LICENSE.MIT)
  if(NOT EXISTS "${_qingying_json_root}/${_qingying_json_file}")
    message(FATAL_ERROR "Missing pinned JSON dependency: ${_qingying_json_file}. See vendor/nlohmann_json/README.md")
  endif()
  file(SHA256 "${_qingying_json_root}/${_qingying_json_file}" _qingying_json_hash)
  if(_qingying_json_file STREQUAL "include/nlohmann/json.hpp")
    set(_qingying_json_expected "9bea4c8066ef4a1c206b2be5a36302f8926f7fdc6087af5d20b417d0cf103ea6")
  else()
    set(_qingying_json_expected "86b998c792894ccb911a1cb7994f7a9652894e7a094c0b5e45be2f553f45cf14")
  endif()
  if(NOT _qingying_json_hash STREQUAL _qingying_json_expected)
    message(FATAL_ERROR "Pinned JSON dependency SHA-256 mismatch: ${_qingying_json_file}")
  endif()
endforeach()
add_library(qingying_json INTERFACE)
add_library(nlohmann_json::nlohmann_json ALIAS qingying_json)
target_include_directories(qingying_json SYSTEM INTERFACE "${_qingying_json_root}/include")
target_compile_features(qingying_json INTERFACE cxx_std_17)
# IPC and future MCP implementations must link this target PRIVATE.
